name: "CD pipeline"

on:
  workflow_run:
    workflows: ["Sample React CI Workflow/Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: "Setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: "Setup vercel cli"
        run: npm install -g vercel

      - name: "Download build files"
        uses: actions/download-artifact@v4
        with:
          name: react-build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: "Deploy to Vercel"
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicd-production