name: "Sample React CI Workflow/Pipeline"

on:
  push:
    branch:
        - master
        - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
      - name: "Setup Node Js"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      
      - name: "Check node version"
        run: node -v

      - name: "CLone the repository"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: npm ci

      - name: "List directories"
        run: ls 

      - name: "Run Lints"
        run: npm run lint

      # - name: "Run tests"
      #   run : npm test

      - name: "Build the application"
        run: npm run build

      - name: "Upload production-ready build files"
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: dist