name: "Sample React CI Workflow/Pipeline"

on:
  push:
    branch:
        - master
        - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest


    steps:
      - name: "Setup Node Js"
        uses: actions/setup-node@v4
        with:
          node-version: "21"
      
      - name: "Check node version"
        run: node -v

      - name: "CLone the repository"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: npm install 

      - name: "List directories"
        run: ls 

      - name: "Run tests"
        run : npm test

      - name: "Build the application"
        run: npm run build